---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

# Manage user privileges
- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'admin ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

# Configure UFW (firewall)
- name: Allow OpenSSH through firewall
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow Nginx through firewall
  ufw:
    rule: allow
    name: "Nginx Full"

- name: Enable UFW
  ufw:
    state: enabled
