---
- name: Copy file to remote servers
  hosts: all
  become: yes

  tasks: 
  - name: Copy files to remote server
    copy:
      src: /home/abhishek/devops/ansible/inventory.ini
      dest: /home/ubuntu/abhi
