---
- name: adding devuser on remote server
  ansible.builtin.user:
      name: devuser
      password: "{{ '$1$CbKJOeA4$mAcdS.7wAQTP183xvYJAz0' }}"
      shell: /bin/bash
      state: present

- name: Grant devuser sudo privileges
  ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: "devuser ALL=(ALL) NOPASSWD:ALL"'
        validate: '/usr/sbin/visudo -cf %s'
