---
- name: Install java on node server
  hosts: all
  become: yes

  vars:
    java_version: "openjdk-11-jdk"

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_version }}"
        state: present

    - name: verify java installation
      command: java -version
      register: java_installed
      ignore_errors: yes

    - name: check if java was installed successfully
      debug:
        msg: "java was installed successfully"
      when: java_installed.rc==0    
